# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2921af71b5bcc7eaa3c6de7006a46cfd102fb925becaf2ea206447b9b59151b8ef3635dae36ca5c93b9c364052857e2f19df35496c4edc317cccef36c89d47d7

test:
  secret_key_base: 9559b153bd1afca5c215901e1a82d2820bc89c2104573d6bf7b7e1d970188173e757741758c3139e159a5d9e82a7af4ba36bfea1afcb8ff7278ffb0faf606e54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
